version: '3.8'
services:
    #  web:
    #    image: nginx:alpine
    #    container_name: ${NGINX_HOST}
    #    volumes:
    #      - "./etc/nginx/templates:/etc/nginx/templates"
    #      - "./etc/ssl:/etc/ssl"
    #      - "./web:/var/www/html"
    #      - "./run/nginx/cache:/var/cache/nginx"
    #      - "./run/nginx/pid:/var/run"
    #    ports:
    #      - "8080:80"
    #      - "4433:443"
    #    networks:
    #      - private
    #    restart: always
    #    env_file:
    #      - ".env"
    #    environment:
    #      - NGINX_HOST=${NGINX_HOST}
    #      - NGINX_PORT=80

    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        volumes:
            - './data/db/mysql:/var/lib/mysql'
        #    - './etc/mysql/my.noroot.cnf:/etc/mysql/mysql.conf.d/noroot.cnf'
        ports:
            - '8806:3306'
        networks:
            - private
        restart: always
        env_file:
            - '.env'
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    mongodb:
        image: mongo:${MONGO_VERSION}
        container_name: ${MONGO_HOST}
        volumes:
            - './data/db/mongo:/data/db'
        ports:
            - '8017:27017'
        networks:
            - private
        restart: always
        env_file:
            - '.env'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_USER=${MONGO_USER}
            - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}

    mongoexpress:
        image: mongo-express
        container_name: ${MONGOEXPRESS_HOST}
        ports:
            - '8082:8081'
        depends_on:
            - mongodb
        env_file:
            - '.env'
        environment:
            - ME_CONFIG_SITE_BASEURL=/mongo/
            - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_ADMIN}
            - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_ADMIN_PASSWORD}
            - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN='true'
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASSWORD}
        networks:
            - private

networks:
    private:
        external: true
        name: 'venusdev'
