version: "3.8"
services:
  #  web:
  #    image: nginx:alpine
  #    container_name: ${NGINX_HOST}
  #    volumes:
  #      - "./etc/nginx/templates:/etc/nginx/templates"
  #      - "./etc/ssl:/etc/ssl"
  #      - "./web:/var/www/html"
  #      - "./run/nginx/cache:/var/cache/nginx"
  #      - "./run/nginx/pid:/var/run"
  #    ports:
  #      - "8080:80"
  #      - "4433:443"
  #    networks:
  #      - private
  #    restart: always
  #    env_file:
  #      - ".env"
  #    environment:
  #      - NGINX_HOST=${NGINX_HOST}
  #      - NGINX_PORT=80

  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    ports:
      - "8806:3306"
    networks:
      - private
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  mogodb:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_HOST}
    volumes:
      - "./data/db/mongo:/data/db"
    ports:
      - "8017:27017"
    networks:
      - private
    restart: always
    env_file:
      - ".env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_USER=${MONGO_USER}
      - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}

networks:
  private:
    external: true
    name: "pre-defined-name"
