version: "3"
services:
  web:
    image: nginx:alpine
    container_name: ${NGINX_HOST}
    volumes:
      - "./etc/nginx/templates:/etc/nginx/templates"
      - "./etc/ssl:/etc/ssl"
      - "./web:/var/www/html"
      - "./run/nginx/cache:/var/cache/nginx"
      - "./run/nginx/pid:/var/run"
    ports:
      - "8080:80"
      - "4433:443"
    env_file:
      - ".env"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=80
    restart: always
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8806:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
  mogodb:
    image: mongo:${MONGO_VERSION}
    container_name: ${MONGO_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_USER=${MONGO_USER}
      - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - "./data/db/mongo:/data/db"
    ports:
      - "8817:27017"
